name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5

      - name: Set up GCC 14
        uses: egor-tensin/setup-gcc@eaa888eb19115a521fa72b65cd94fe1f25bbcaac # v1
        with:
          version: 14
          platform: x64

      - uses: MarkusJx/googletest-installer@28c5d4102d9d57b46254be19a940bf038a9c850a
      - uses: ssciwr/doxygen-install@f13be1686235deee0aeb6cdf56640170691dc96b
        with:
          version: "1.15.0"
      - uses: KyleMayes/install-llvm-action@ebc0426251bc40c7cd31162802432c68818ab8f0
        with:
          version: "20.1.8"
          env: true

      - name: Install Qt 6
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.*'
          target: 'desktop'
          install-deps: 'true'
          cache: 'true'
          modules: 'qtmultimedia'

      - name: Install backend deps
        run: |
          sudo apt-get update
          sudo apt-get install -y  \
            libcxxopts-dev graphviz lcov gcovr libopencv-dev

      - name: Configure (Debug, non-KDE, tests ON, coverage ON)
        env:
          CC: gcc-14
          CXX: g++-14
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_C_COMPILER=gcc-14 \
            -DCMAKE_CXX_COMPILER=g++-14 \
            -DKDE=OFF \
            -DBUILD_TESTS=ON \
            -DENABLE_COVERAGE=ON \
            -DENABLE_ASAN=OFF

      - name: Generate Doxygen
        run: doxygen Doxyfile

      - name: Build with coverage
        env:
          QT_QPA_PLATFORM: offscreen
        run: |
          cmake --build build --target coverage --parallel $(nproc)

      - name: Upload results to Codecov
        if: ${{ hashFiles('build/coverage.info') != '' }}
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        continue-on-error: true
        with:
          files: build/coverage.info
          fail_ci_if_error: false
          use_oidc: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage to Codacy
        if: ${{ hashFiles('build/coverage.info') != '' }}
        uses: codacy/codacy-coverage-reporter-action@a38818475bb21847788496e9f0fddaa4e84955ba
        continue-on-error: true
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/coverage.info

      - name: Clean build
        run: rm -rf build/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
        with:
          path: doc

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
