name: Deploy

on:
  push:
    branches:
      - todomaster
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: MarkusJx/googletest-installer@28c5d4102d9d57b46254be19a940bf038a9c850a
      - uses: ssciwr/doxygen-install@501e53b879da7648ab392ee226f5b90e42148449
        with:
          version: "1.15.0"
      - uses: KyleMayes/install-llvm-action@98e68e10c96dffcb7bfed8b2144541a66b49aa02
        with:
          version: "20.1.8"
          env: true

      - name: Install Qt 6
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.*'
          target: 'desktop'
          install-deps: 'true'
          cache: 'true'

      # - name: Install backend deps
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y \
      #       v4l2loopback-dkms \
      #       libopencv-dev

      - name: Configure (Debug, non-KDE, tests ON, coverage ON)
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DKDE=OFF \
            -DBUILD_TESTS=ON \
            -DENABLE_COVERAGE=ON \
            -DENABLE_ASAN=OFF

      - name: Generate Doxygen
        run: doxygen Doxyfile

      - name: Build with coverage
        run: |
          cmake --build build --target coverage --parallel $(nproc)

      - name: Upload results to Codecov
        if: ${{ hashFiles('build/coverage.info') != '' }}
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        continue-on-error: true
        with:
          files: build/coverage.info
          fail_ci_if_error: false
          use_oidc: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage to Codacy
        if: ${{ hashFiles('build/coverage.info') != '' }}
        uses: codacy/codacy-coverage-reporter-action@a38818475bb21847788496e9f0fddaa4e84955ba
        continue-on-error: true
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/coverage.info

      - name: Clean build
        run: rm -rf build/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4