name: Checks

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up GCC 14
        uses: egor-tensin/setup-gcc@eaa888eb19115a521fa72b65cd94fe1f25bbcaac # v1
        with:
          version: 14
          platform: x64

      - uses: MarkusJx/googletest-installer@28c5d4102d9d57b46254be19a940bf038a9c850a

      - name: Install Qt 6
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.*'
          target: 'desktop'
          install-deps: 'true'
          cache: 'true'
          modules: 'qtmultimedia'

      - name: Install backend deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcxxopts-dev libopencv-dev

      - name: Configure (Debug, non-KDE, tests ON, coverage OFF)
        env:
          CC: gcc-14
          CXX: g++-14
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_C_COMPILER=gcc-14 \
            -DCMAKE_CXX_COMPILER=g++-14 \
            -DKDE=OFF \
            -DBUILD_TESTS=ON \
            -DENABLE_COVERAGE=OFF \
            -DENABLE_ASAN=OFF

      - name: Build project
        run: cmake --build build --parallel

      - name: Run unit tests
        env:
          QT_QPA_PLATFORM: offscreen
        run: ctest --test-dir build --output-on-failure --parallel $(nproc)

  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Clang-format
        uses: jidicula/clang-format-action@8cf0fe91805dd97bc574a1423c447b35e75b77fa
        with:
          clang-format-version: '21'
          check-path: '.'
