name: Checks

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: MarkusJx/googletest-installer@28c5d4102d9d57b46254be19a940bf038a9c850a

      - name: Install Qt 6
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.*'
          target: 'desktop'
          install-deps: 'true'
          cache: 'true'

      # - name: Install backend deps
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y \
      #       v4l2loopback-dkms \
      #       libopencv-dev

      - name: Configure (Debug, non-KDE, tests ON, coverage OFF)
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DKDE=OFF \
            -DBUILD_TESTS=ON \
            -DENABLE_COVERAGE=OFF \
            -DENABLE_ASAN=OFF

      - name: Build project
        run: cmake --build build --parallel

      - name: Run unit tests
        run: ctest --test-dir build --output-on-failure --parallel $(nproc)

  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Clang-format
        uses: jidicula/clang-format-action@6cd220de46c89139a0365edae93eee8eb30ca8fe
        with:
          clang-format-version: '21'
          check-path: '.'